name: TestDeploy

on:
  push:
    branches: [master]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: CodeDeploy
        run: aws deploy create-deployment --application-name "Python_Api" --deployment-group-name "Python_Api" --github-location repository="rocorock/api_practice",commitId="${{ github.sha }}"
